/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_paomiantv_mediasdk_PMClip */

#ifndef _Included_cn_paomiantv_mediasdk_PMClip
#define _Included_cn_paomiantv_mediasdk_PMClip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _init
 * Signature: (Ljava/lang/String;JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMClip__1init
  (JNIEnv *, jobject, jstring, jlong, jlong);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _uninit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMClip__1uninit
  (JNIEnv *, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _getSrc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_paomiantv_mediasdk_PMClip__1getSrc
  (JNIEnv *, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _setSrc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_paomiantv_mediasdk_PMClip__1setSrc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _getStart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_paomiantv_mediasdk_PMClip__1getStart
  (JNIEnv *, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _setStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_paomiantv_mediasdk_PMClip__1setStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _getDuration
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_paomiantv_mediasdk_PMClip__1getDuration
  (JNIEnv *, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _setDuration
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_paomiantv_mediasdk_PMClip__1setDuration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _getFilter
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_paomiantv_mediasdk_PMClip__1getFilter
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _addFilter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMClip__1addFilter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _removeFilter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMClip__1removeFilter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _getFilterCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_paomiantv_mediasdk_PMClip__1getFilterCount
  (JNIEnv *, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _addTransition
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMClip__1addTransition
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _getTransition
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_paomiantv_mediasdk_PMClip__1getTransition
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _removeTransition
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMClip__1removeTransition
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_paomiantv_mediasdk_PMClip
 * Method:    _getTransitionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_paomiantv_mediasdk_PMClip__1getTransitionCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
