/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_paomiantv_mediasdk_PMStoryboard */

#ifndef _Included_cn_paomiantv_mediasdk_PMStoryboard
#define _Included_cn_paomiantv_mediasdk_PMStoryboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_paomiantv_mediasdk_PMStoryboard
 * Method:    _init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMStoryboard__1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_paomiantv_mediasdk_PMStoryboard
 * Method:    _uninit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMStoryboard__1uninit
  (JNIEnv *, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMStoryboard
 * Method:    _addClip
 * Signature: (Lcn/paomiantv/mediasdk/PMClip;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMStoryboard__1addClip
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMStoryboard
 * Method:    _removeClip
 * Signature: (I)Lcn/paomiantv/mediasdk/PMClip;
 */
JNIEXPORT jobject JNICALL Java_cn_paomiantv_mediasdk_PMStoryboard__1removeClip
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_paomiantv_mediasdk_PMStoryboard
 * Method:    _getClip
 * Signature: (I)Lcn/paomiantv/mediasdk/PMClip;
 */
JNIEXPORT jobject JNICALL Java_cn_paomiantv_mediasdk_PMStoryboard__1getClip
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_paomiantv_mediasdk_PMStoryboard
 * Method:    _swapClip
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMStoryboard__1swapClip
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_paomiantv_mediasdk_PMStoryboard
 * Method:    _procsss
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMStoryboard__1procsss
  (JNIEnv *, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMStoryboard
 * Method:    _cancel
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_paomiantv_mediasdk_PMStoryboard__1cancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
