/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_paomiantv_mediasdk_PMEngine */

#ifndef _Included_cn_paomiantv_mediasdk_PMEngine
#define _Included_cn_paomiantv_mediasdk_PMEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_paomiantv_mediasdk_PMEngine
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_paomiantv_mediasdk_PMEngine__1init
  (JNIEnv *, jobject);

/*
 * Class:     cn_paomiantv_mediasdk_PMEngine
 * Method:    _uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_paomiantv_mediasdk_PMEngine__1uninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
