/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_paomiantv_mediasdk_PMStoryboard_ProcessListener */

#ifndef _Included_cn_paomiantv_mediasdk_PMStoryboard_ProcessListener
#define _Included_cn_paomiantv_mediasdk_PMStoryboard_ProcessListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
