/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_paomiantv_mediasdk_PMEngine_Mp4v2HelperHolder */

#ifndef _Included_cn_paomiantv_mediasdk_PMEngine_Mp4v2HelperHolder
#define _Included_cn_paomiantv_mediasdk_PMEngine_Mp4v2HelperHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
